name: Coverage Report

on:
  push:
    branches: [ development ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug        

      - name: Install dependencies
        run: |
          composer install --prefer-dist

      - name: Execute tests with coverage
        run: vendor/bin/phpunit  --configuration 'phpunit.xml' --coverage-cobertura=coverage-cobertura.xml

      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.3.0
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage-cobertura.xml